// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYuBYVoK20tCbxjBJ_vJK7agGOulHJYvg',
    appId: '1:661740799168:web:8e7273677a64f71c44d925',
    messagingSenderId: '661740799168',
    projectId: 'quotely-app-f2039',
    authDomain: 'quotely-app-f2039.firebaseapp.com',
    storageBucket: 'quotely-app-f2039.firebasestorage.app',
    measurementId: 'G-60XY5EYMQF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDp3NDaZmwxhu_KGVc2_koY1IL2pWwtmx4',
    appId: '1:661740799168:android:68d20cdc0e2d3d5344d925',
    messagingSenderId: '661740799168',
    projectId: 'quotely-app-f2039',
    storageBucket: 'quotely-app-f2039.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJxHnej5Q4aWVIUrj8PKu1McsOxIwXBPc',
    appId: '1:661740799168:ios:41280c5d7569ada744d925',
    messagingSenderId: '661740799168',
    projectId: 'quotely-app-f2039',
    storageBucket: 'quotely-app-f2039.firebasestorage.app',
    iosBundleId: 'com.example.linuxTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJxHnej5Q4aWVIUrj8PKu1McsOxIwXBPc',
    appId: '1:661740799168:ios:41280c5d7569ada744d925',
    messagingSenderId: '661740799168',
    projectId: 'quotely-app-f2039',
    storageBucket: 'quotely-app-f2039.firebasestorage.app',
    iosBundleId: 'com.example.linuxTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYuBYVoK20tCbxjBJ_vJK7agGOulHJYvg',
    appId: '1:661740799168:web:4df0886bc15ebcd044d925',
    messagingSenderId: '661740799168',
    projectId: 'quotely-app-f2039',
    authDomain: 'quotely-app-f2039.firebaseapp.com',
    storageBucket: 'quotely-app-f2039.firebasestorage.app',
    measurementId: 'G-T8F1KYQWHD',
  );
}
